### ISSUE TITLE
Override conflicts with direct dependency

### ISSUE THREAD

**Issue by abenrob** [CartoDB/carto-react-template#370]
When building from ts template `npx create-react-app my_app --template @carto/base-3-typescript`, error is thrown: `Override for typescript@^4.4.3 conflicts with direct dependency`.

Any reason the direct can't be bumped to 5.0.0?

**Comment by abenrob** [comment]
Tried to manually set direct in package.json to 5.0.0, but still fails for other conflict reasons

```
npm ERR! code EOVERRIDE
npm ERR! Override for typescript@^5.4.5 conflicts with direct dependency
```

**Comment by abenrob** [comment]
```
cat  /Users/adam/.npm/_logs/2024-05-31T12_29_59_929Z-debug-0.log
0 verbose cli /Users/adam/.nvm/versions/node/v21.7.2/bin/node /Users/adam/.nvm/versions/node/v21.7.2/bin/npm
1 info using npm@10.5.0
2 info using node@v21.7.2
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/adam/.nvm/versions/node/v21.7.2/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 1ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/adam/projects/c4r_ts/.npmrc Completed in 0ms
10 timing config:load:project Completed in 1ms
11 timing config:load:file:/Users/adam/.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:/Users/adam/.nvm/versions/node/v21.7.2/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 5ms
17 timing npm:load:configload Completed in 5ms
18 timing config:load:flatten Completed in 1ms
19 timing npm:load:mkdirpcache Completed in 0ms
20 timing npm:load:mkdirplogs Completed in 0ms
21 verbose title npm uninstall @carto/cra-template-base-3-typescript
22 verbose argv "uninstall" "@carto/cra-template-base-3-typescript"
23 timing npm:load:setTitle Completed in 5ms
24 timing npm:load:display Completed in 0ms
25 verbose logfile logs-max:10 dir:/Users/adam/.npm/_logs/2024-05-31T12_29_59_929Z-
26 verbose logfile /Users/adam/.npm/_logs/2024-05-31T12_29_59_929Z-debug-0.log
27 timing npm:load:logFile Completed in 4ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 22ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing command:uninstall Completed in 10ms
35 verbose stack Error: Override for typescript@^5.4.5 conflicts with direct dependency
35 verbose stack     at Node.assertRootOverrides (/Users/adam/.nvm/versions/node/v21.7.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/node.js:1334:29)
35 verbose stack     at #loadActual (/Users/adam/.nvm/versions/node/v21.7.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/load-actual.js:133:24)
35 verbose stack     at async Promise.all (index 0)
35 verbose stack     at async Arborist.reify (/Users/adam/.nvm/versions/node/v21.7.2/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:154:5)
35 verbose stack     at async Uninstall.exec (/Users/adam/.nvm/versions/node/v21.7.2/lib/node_modules/npm/lib/commands/uninstall.js:52:5)
35 verbose stack     at async module.exports (/Users/adam/.nvm/versions/node/v21.7.2/lib/node_modules/npm/lib/cli-entry.js:61:5)
36 verbose cwd /Users/adam/projects/c4r_ts
37 verbose Darwin 22.5.0
38 verbose node v21.7.2
39 verbose npm  v10.5.0
40 error code EOVERRIDE
41 error Override for typescript@^5.4.5 conflicts with direct dependency
42 verbose exit 1
43 timing npm Completed in 124ms
44 verbose unfinished npm timer reify 1717158600043
45 verbose unfinished npm timer reify:loadTrees 1717158600045
46 verbose unfinished npm timer idealTree 1717158600046
47 verbose unfinished npm timer idealTree:init 1717158600046
48 verbose code 1
49 error A complete log of this run can be found in: /Users/adam/.npm/_logs/2024-05-31T12_29_59_929Z-debug-0.log
```
